<a href="https://colab.research.google.com/github/kalki81000/python/blob/main/Copy_of_Untitled7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np

l = [1,2,3,4,5]

arr = np.array(l)

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
a =np.zeros(34)

In [ ]:
b = np.zeros((3,3))

In [ ]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c = np.ones((2,6))

In [ ]:
c

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.zeros(((2,3,4)))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr=np.ones(((2,7,6,)))

In [ ]:
arr.ndim

3

In [ ]:
arr = np.zeros((1,2,3))

In [ ]:
arr

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
arr = np.zeros((1,2,3))

In [ ]:
arr.ndim

3

In [ ]:
arr = np.ones((1,2,3,4))

In [ ]:
arr

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [ ]:
arr+5

array([[[[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]],

        [[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]]])

In [ ]:
arr.ndim

4

In [ ]:
arr -3

array([[[[-2., -2., -2., -2.],
         [-2., -2., -2., -2.],
         [-2., -2., -2., -2.]],

        [[-2., -2., -2., -2.],
         [-2., -2., -2., -2.],
         [-2., -2., -2., -2.]]]])

In [ ]:
arr.shape

(1, 2, 3, 4)

In [ ]:
arr * 4

array([[[[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]],

        [[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]]]])

In [ ]:
arr / 6

array([[[[0.16666667, 0.16666667, 0.16666667, 0.16666667],
         [0.16666667, 0.16666667, 0.16666667, 0.16666667],
         [0.16666667, 0.16666667, 0.16666667, 0.16666667]],

        [[0.16666667, 0.16666667, 0.16666667, 0.16666667],
         [0.16666667, 0.16666667, 0.16666667, 0.16666667],
         [0.16666667, 0.16666667, 0.16666667, 0.16666667]]]])

In [ ]:
arr % 1

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# optional

import random

random.choice((1,2,3,4,5))

4

In [ ]:
random.choice("ajay")

'a'

In [ ]:
random.random()

0.40645078136960666

In [ ]:
lis = [1,2,3,45]
random.shuffle(lis)

In [ ]:
lis

[1, 3, 2, 45]

In [ ]:
np.random.random_sample()

0.6645775673859724

In [ ]:
np.random.random_sample((2,5))

array([[0.92097747, 0.15093615, 0.59295234, 0.17553356, 0.48453977],
       [0.68290676, 0.73498228, 0.37898722, 0.92419659, 0.1881193 ]])

In [ ]:
np.random.rand(1)

array([0.712708])

In [ ]:
np.random.rand(1,2)

array([[0.38762598, 0.18837279]])

In [ ]:
arr=np.random.randint(1,2, size = (3,4))

In [ ]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
arr.size

12

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.ndim

2

In [ ]:
arr1=arr.reshape(2,6)

In [ ]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
arr.size

12

In [ ]:
arr1.size

12

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr1.shape

(2, 6)

In [ ]:
arr.reshape(1 , -1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
arr.reshape(-1,3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
arr.reshape(12 , 1).base

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
arr.reshape(2,2,3)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [ ]:
arr.reshape(1,2,2,3)

array([[[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]]])

In [ ]:
arr.reshape(1,2,2,3).ndim

4

In [ ]:
arr1 = np.random.randint(1,10, (5,6))

In [ ]:
arr1

array([[1, 9, 1, 3, 1, 3],
       [6, 9, 6, 8, 9, 9],
       [4, 3, 8, 1, 5, 7],
       [3, 3, 5, 7, 6, 9],
       [9, 5, 4, 1, 9, 8]])

In [ ]:
arr1.size

30

In [ ]:
arr1 > 3

array([[False,  True, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True, False,  True, False,  True,  True],
       [False, False,  True,  True,  True,  True],
       [ True,  True,  True, False,  True,  True]])

In [ ]:
arr1[arr1>3]

array([9, 6, 9, 6, 8, 9, 9, 4, 8, 5, 7, 5, 7, 6, 9, 9, 5, 4, 9, 8])

In [ ]:
arr1[0]

array([1, 9, 1, 3, 1, 3])

In [ ]:
arr1[1][2]

6

In [ ]:
arr1[0:2]

array([[1, 9, 1, 3, 1, 3],
       [6, 9, 6, 8, 9, 9]])

In [ ]:
arr1[:1]

array([[1, 9, 1, 3, 1, 3]])

In [ ]:
arr1[1:]

array([[6, 9, 6, 8, 9, 9],
       [4, 3, 8, 1, 5, 7],
       [3, 3, 5, 7, 6, 9],
       [9, 5, 4, 1, 9, 8]])

In [ ]:
arr1[0:3, [2,3]]

array([[1, 3],
       [6, 8],
       [8, 1]])

In [ ]:
arr1[0:2 , 1:3]

array([[9, 1],
       [9, 6]])

In [ ]:
arr2 = np.random.randint(1 ,5 ,(5,6))

In [ ]:
arr2

array([[2, 3, 3],
       [3, 3, 5]])

In [ ]:
arr1 + arr2

array([[ 3, 12,  3,  8,  2,  8],
       [10, 14,  9,  9, 14, 12],
       [ 6,  5, 13,  3,  9, 10],
       [ 6,  8,  9, 12, 10, 14],
       [14,  8,  7,  2, 14,  9]])

In [ ]:
arr1

array([[1, 9, 1, 3, 1, 3],
       [6, 9, 6, 8, 9, 9],
       [4, 3, 8, 1, 5, 7],
       [3, 3, 5, 7, 6, 9],
       [9, 5, 4, 1, 9, 8]])

In [ ]:
arr1 - arr2

array([[-1,  6, -1, -2,  0, -2],
       [ 2,  4,  3,  7,  4,  6],
       [ 2,  1,  3, -1,  1,  4],
       [ 0, -2,  1,  2,  2,  4],
       [ 4,  2,  1,  0,  4,  7]])

In [ ]:
arr1 * arr2

array([[ 2, 27,  2, 15,  1, 15],
       [24, 45, 18,  8, 45, 27],
       [ 8,  6, 40,  2, 20, 21],
       [ 9, 15, 20, 35, 24, 45],
       [45, 15, 12,  1, 45,  8]])

In [ ]:
arr1 @ arr2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 6)

In [ ]:
arr1

array([[1, 9, 1, 3, 1, 3],
       [6, 9, 6, 8, 9, 9],
       [4, 3, 8, 1, 5, 7],
       [3, 3, 5, 7, 6, 9],
       [9, 5, 4, 1, 9, 8]])

In [ ]:
arr2

array([[2, 4, 3, 4, 4, 3],
       [4, 3, 3, 1, 4, 1],
       [4, 3, 4, 4, 3, 4],
       [1, 3, 4, 3, 4, 2],
       [4, 2, 4, 1, 1, 2]])

In [ ]:
arr1 = np.random.randint(3,8)

In [ ]:
arr2 =np.random.randint((3,8))

In [ ]:
arr1

4

In [ ]:
arr2

array([2, 2])

In [ ]:
arr1 = np.random.randint(1,3 , (5,6))

In [ ]:
arr2= np.random.randint(1,3, (6,5))

In [ ]:
arr1 @ arr2

array([[17, 13, 17, 16, 16],
       [12, 10, 13, 13, 11],
       [12,  9, 12, 13, 12],
       [18, 14, 18, 18, 18],
       [13, 10, 13, 13, 15]])

In [ ]:
np.dot(arr1,arr2)

array([[17, 13, 17, 16, 16],
       [12, 10, 13, 13, 11],
       [12,  9, 12, 13, 12],
       [18, 14, 18, 18, 18],
       [13, 10, 13, 13, 15]])

In [ ]:
arr1 / 0

<ipython-input-107-f39b50d43667>:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [ ]:
arr3=np.zeros((3,4))

In [ ]:
arr3 + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a = np.array((2,1,3,4))

In [ ]:
a

array([2, 1, 3, 4])

In [ ]:
a.ndim

1

In [ ]:
a.T

array([1, 2, 3, 4])

In [ ]:
a.T

array([2, 1, 3, 4])

In [ ]:
arr1.T

array([[2, 1, 1, 2, 1],
       [2, 2, 1, 2, 1],
       [1, 1, 2, 2, 2],
       [2, 1, 1, 2, 2],
       [2, 1, 1, 2, 2],
       [2, 2, 2, 2, 1]])

In [ ]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.        , 1.41421356, 1.41421356,
        1.41421356],
       [1.        , 1.41421356, 1.        , 1.        , 1.        ,
        1.41421356],
       [1.        , 1.        , 1.41421356, 1.        , 1.        ,
        1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356,
        1.41421356],
       [1.        , 1.        , 1.41421356, 1.41421356, 1.41421356,
        1.        ]])

In [ ]:
np.min(arr1)

1

In [ ]:
np.max(arr1)

2

In [ ]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [ ]:
arr1

array([[2, 2, 2],
       [2, 2, 2],
       [1, 2, 2]])

In [ ]:
arr1.flatten()

array([2, 2, 2, 2, 2, 2, 1, 2, 2])

In [ ]:
arr = np.array([1,2,3,4])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr.ndim

1

In [ ]:
arr2=np.expand_dims(arr,axis = 0)

In [ ]:
arr.ndim

1

In [ ]:
arr2

array([[1, 2, 3, 4]])

In [ ]:
arr2.ndim

2

In [ ]:
arr1=np.zeros((2,3))

In [ ]:
arr1.ndim

2

In [ ]:
np.expand_dims(arr1,axis=0)

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.expand_dims(arr1,axis=1)

array([[[0., 0., 0.]],

       [[0., 0., 0.]]])

In [ ]:
np.squeeze(arr1)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.repeat(a,7)

array([2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4])

In [ ]:
np.squeeze(a)


array([2, 1, 3, 4])

In [ ]:
np.repeat(a , 2 , axis =0)

array([2, 2, 1, 1, 3, 3, 4, 4])

In [ ]:
np.repeat(arr1 , 3, axis = 1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.repeat(arr1 , 3, axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.roll(a,-2)

array([3, 4, 2, 1])

In [ ]:
np.roll(a,-1)

array([1, 3, 4, 2])

In [ ]:
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr2

array([[1, 2, 3, 4]])

In [ ]:
arr1 > arr2

ValueError: operands could not be broadcast together with shapes (2,3) (1,4) 

In [ ]:
arr3 = np.zeros((3,3))

In [ ]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr1 > arr3

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [ ]:
d = np.array(["pw","skill"])

In [ ]:
d

array(['pw', 'skill'], dtype='<U5')

In [ ]:
np.char.upper(d)

array(['PW', 'SKILL'], dtype='<U5')

In [ ]:
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr1 = np.array([[1,2],[3,4]])

In [ ]:
arr1

array([[1, 2],
       [3, 4]])

In [ ]:
np.sin(arr1)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [ ]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [ ]:
np.tan(arr1)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [ ]:
np.power(arr1,3)

array([[ 1,  8],
       [27, 64]])

In [ ]:
np.mean(arr1)

2.5

In [ ]:
np.var(arr1)

1.25

In [ ]:
np.max(arr1)

4

In [ ]:
e = np.array([5,4,3,2,1])

In [ ]:
e

array([5, 4, 3, 2, 1])

In [ ]:
np.sort(e)

array([1, 2, 3, 4, 5])

In [ ]:
np.searchsorted(e , 3)

0

In [ ]:
np.count_nonzero(e)

5

In [ ]:
np.where(e > 0)

(array([0, 1, 2, 3, 4]),)

In [ ]:
np.extract (e > 0, e)

array([5, 4, 3, 2, 1])

In [ ]:
e.byteswap()


array([360287970189639680, 288230376151711744, 216172782113783808,
       144115188075855872,  72057594037927936])

In [ ]:
import numpy.matlib as nm

nm.zeros(4)

matrix([[0., 0., 0., 0.]])

In [ ]:
nm.ones((2,3))

matrix([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
arr1 = np.random.randint(1,10, (3,4))

In [ ]:
arr2 = np.random.randint(1,10, (4,3))

In [ ]:
arr1 @ arr2

array([[ 76, 126,  98],
       [ 76, 101, 151],
       [ 47,  61,  76]])

In [ ]:
np.linalg.det(arr2)

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
np.linalg.inv(arr1)

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
a = np.array([[17,5.3,-1],[1,2,3]])

In [ ]:
b = np.array([1,2,3])

In [ ]:
np.linalg.solve(a,b)

LinAlgError: Last 2 dimensions of the array must be square